# Image Practice

In [1]:
import cv2

In [2]:
img = cv2.imread("C:/Users/HP/Desktop/pics/hadoop2.jpg", cv2.IMREAD_COLOR)

In [3]:
img1 = cv2.imread("C:/Users/HP/Desktop/pics/hadoop2.jpg", cv2.IMREAD_GRAYSCALE)

print(type(img), " " ,type(img1) )

<class 'numpy.ndarray'>   <class 'numpy.ndarray'>


In [4]:
# print(img, "and" ,img1)

In [5]:
xyz = cv2.imshow('', img)
k = cv2.waitKey(0)
print(k)
# cv2.waitKey(0) & 0xFF == ord('q')
cv2.destroyAllWindows()


113


In [6]:
# type(cv2.imwrite('h1.png',img))
color_img = cv2.imwrite('xyz.png',img)
gray_img = cv2.imwrite('xyz1.png', img1)
# help(cv2.imwrite)

In [7]:
print(img , "and ", gray_img)

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]] and  True


# video practice

In [4]:
import cv2
video = cv2.VideoCapture(0)

while(True):
    bool_val,num_matrix = video.read()   
    num_matrix = cv2.cvtColor(num_matrix, cv2.COLOR_RGB2GRAY)
    
    cv2.imshow('video',num_matrix)
    
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

video.release()
cv2.destroyAllWindows()

In [5]:
import cv2
video = cv2.VideoCapture(0)
fourcc = cv2.VideoWriter_fourcc(*'XVID')
out = cv2.VideoWriter('output.avi',fourcc, 20.0, (640,480))

while(True):
    ret,frame = video.read()
    out.write(frame)
    cv2.imshow('video', frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
        
out.release()
video.release()
cv2.destroyAllWindows()

# Drawing and Writing on Image

In [6]:
import cv2
img_read = cv2.imread("C:/Users/HP/Desktop/pics/pic1.jpg", 1) 

In [7]:
# Draw a line on image so pass parameter "the image name, starting point, ending point, color of strock and width of strock"
cv2.line(img_read,(0,0), (150,150), (255,0,0), 10)

# Draw a Circle on image so pass parameter "the image name, center of the circle, the radius, color, and then thickness"
cv2.circle(img_read,(150,150), 50 , (0,255,0), -1) #-1 means filled the area with that color

# Draw a Rectangle on image so pass parameter "the image name, top left coordinate, bottom right coordinate, color, 
# and thickness"
cv2.rectangle(img_read,(0,0),(150,150) , (0,0,255), 5)

# Resize the window which shows the image
cv2.namedWindow("Image", cv2.WINDOW_NORMAL)   

cv2.imshow('Image', img_read)
cv2.waitKey(0)
cv2.destroyAllWindows()

Polyline shape

In [8]:
import numpy as np
pts = np.array([[50,0],[100,0],[150,50],[100,100],[50,100],[5,50]], np.int32)
# OpenCV documentation had this code, which reshapes the array to a 1 x 2. I did not 
# find this necessary, but you may:
#pts = pts.reshape((-1,1,2))

# Draw a Polygon on image so pass parameter "the image name, the coordinates, should we "connect" the final and starting dot, 
# the color, and the thickness"
cv2.rectangle(img_read,(0,0),(150,150) , (0,0,255), 5)
cv2.polylines(img_read, [pts], True, (0,255,255), 3)

cv2.imshow('img', img_read)
cv2.waitKey(0)
cv2.destroyAllWindows()

 write on the image.

In [9]:
font = cv2.FONT_HERSHEY_SIMPLEX

# Draw a Circle on image so pass parameter "the image name, text, position, Font type, size of font, color, and then thickness"
cv2.putText(img_read, 'Open CV!', (0,50), font, 1, (255,255,255), 2, cv2.LINE_AA)

cv2.imshow('Image', img_read)
cv2.waitKey(0)
cv2.destroyAllWindows()

Image Operations

In [14]:
import cv2
img = cv2.imread("C:/Users/HP/Desktop/pics/pic1.jpg", 1) 

img_pix = img[55:100, 55:100]
# print(img_pix, type(img_pix))

img[55:100, 55:100] = [255,255,255]
# print(img_pix, type(img_pix))

img_pix = img[55:100, 55:100]
# print(img_pix)

print(img.shape)
print(img.size)
print(img.dtype)

watch_face = img[200:250,400:500]

img[0:50,0:100] = watch_face

cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

(1040, 585, 3)
1825200
uint8


Image arithmetics

In [15]:
import cv2
img1 = cv2.imread("C:/Users/HP/Desktop/pics/ec1f6a6856dde5dc7b81a7fcbbe548a9--lord.jpg")
img2 = cv2.imread("C:/Users/HP/Desktop/pics/ghanshyam1.jpg")

add = img1 + img1
cv2.imshow('Image', add)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [16]:
# For the addWeighted method, the parameters are the first image, the weight, the second image, that weight, and then
# finally gamma, which is a measurement of light. We'll leave that at zero for now.
weightadd = cv2.addWeighted(img1, 0.6, img2, 0.4, 0)
cv2.imshow('weighted', weightadd)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [17]:
import cv2

# Load two images
img1 = cv2.imread("C:/Users/HP/Desktop/pics/ghanshyam1.jpg")
img2 = cv2.imread("C:/Users/HP/Desktop/pics/ec1f6a6856dde5dc7b81a7fcbbe548a9--lord.jpg")

# I want to put logo on top-left corner, So I create a ROI
rows,cols,channels = img2.shape
roi = img1[0:rows, 0:cols ]

# Now create a mask of logo and create its inverse mask
img2gray = cv2.cvtColor(img2,cv2.COLOR_BGR2GRAY)

# add a threshold
ret, mask = cv2.threshold(img2gray, 220, 255, cv2.THRESH_BINARY_INV)

mask_inv = cv2.bitwise_not(mask)

# Now black-out the area of logo in ROI
img1_bg = cv2.bitwise_and(roi,roi,mask = mask_inv)

# Take only region of logo from logo image.
img2_fg = cv2.bitwise_and(img2,img2,mask = mask)

dst = cv2.add(img1_bg,img2_fg)
img1[0:rows, 0:cols ] = dst

cv2.imshow('res',img1)
cv2.waitKey(0)
cv2.destroyAllWindows()

Color Filtering

In [18]:
import cv2
import numpy as np

cap = cv2.VideoCapture(0)

while(1):
    ref, frame = cap.read()
    hsv = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)
        
    lower_red = np.array([30,150,50])
    upper_red = np.array([255,255,180])
    
    mask = cv2.inRange(hsv, lower_red, upper_red)
    res = cv2.bitwise_and(frame,frame, mask= mask)

    cv2.imshow('frame',frame)
    cv2.imshow('mask',mask)
    cv2.imshow('res',res)
    
    k = cv2.waitKey(5) & 0xFF
    if k == 27:
        break

cv2.destroyAllWindows()
cap.release()

In [19]:
import cv2
import numpy as np

cap = cv2.VideoCapture(0)

while(1):

    _, frame = cap.read()
    hsv = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)
    
    lower_red = np.array([30,150,50])
    upper_red = np.array([255,255,180])
    
    mask = cv2.inRange(hsv, lower_red, upper_red)
    res = cv2.bitwise_and(frame,frame, mask= mask)

    cv2.imshow('Original',frame)
    edges = cv2.Canny(frame,100,200)
    cv2.imshow('Edges',edges)

    k = cv2.waitKey(5) & 0xFF
    if k == 27:
        break

cv2.destroyAllWindows()
cap.release()

In [20]:
import cv2
import numpy as np

cap = cv2.VideoCapture(1)

while(1):

    # Take each frame
    _, frame = cap.read()
    hsv = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)
    
    lower_red = np.array([30,150,50])
    upper_red = np.array([255,255,180])
    
    mask = cv2.inRange(hsv, lower_red, upper_red)
    res = cv2.bitwise_and(frame,frame, mask= mask)

    laplacian = cv2.Laplacian(frame,cv2.CV_64F)
    sobelx = cv2.Sobel(frame,cv2.CV_64F,1,0,ksize=5)
    sobely = cv2.Sobel(frame,cv2.CV_64F,0,1,ksize=5)

    cv2.imshow('Original',frame)
    cv2.imshow('Mask',mask)
    cv2.imshow('laplacian',laplacian)
    cv2.imshow('sobelx',sobelx)
    cv2.imshow('sobely',sobely)

    k = cv2.waitKey(5) & 0xFF
    if k == 27:
        break

cv2.destroyAllWindows()
cap.release()

error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'


## Template Matching

In [3]:
import cv2
import numpy as np

img_rgb = cv2.imread('C:/Users/HP/Desktop/opencv-template-matching-python-tutorial.jpg')
img_gray = cv2.cvtColor(img_rgb, cv2.COLOR_BGR2GRAY)
cv2.imshow('Original',img_rgb)

template = cv2.imread('C:/Users/HP/Desktop/opencv-template-for-matching.jpg',0)
cv2.imshow('Original',template)

# shape return 2 arguments height and width cordinate if its balck and white
# else shape return 3 arguments one extra is color channel

w, h = template.shape[::-1]    # or ha,wa = template.shape

res = cv2.matchTemplate(img_gray,template,cv2.TM_CCORR_NORMED)
threshold = 0.9
loc = np.where( res >= threshold)
# print(loc)

for pt in zip(*loc[::-1]):
#     print(pt)
    cv2.rectangle(img_rgb, pt, (pt[0] + w, pt[1] + h), (0,255,255), 2)

cv2.imshow('Detected',img_rgb)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [1]:
import cv2
import numpy as np

main1 = cv2.imread('C:/Users/HP/Desktop/opencv-template-matching-python-tutorial.jpg')
main = cv2.cvtColor(main1, cv2.COLOR_BGRA2BGR)
cv2.imshow('Original',main)

templete = cv2.imread('C:/Users/HP/Desktop/opencv-template-for-matching.jpg',1)
cv2.imshow('Original2',templete)

w, h,a = templete.shape[::-1] 

match_images = cv2.matchTemplate(main, templete,cv2.TM_CCORR_NORMED)
threshold = 0.95
loc = np.where(match_images >= threshold)

for pt in zip(*loc[::-1]):
    cv2.rectangle(main1, pt, (pt[0]+w, pt[1]+h), (0,0,255), 1)
    
cv2.imshow('final', main1)

cv2.waitKey(0)
cv2.destroyAllWindows()
# cap.release()
    

# MOG Background Reduction


In [10]:
import numpy as np
import cv2

cap = cv2.VideoCapture(0)
fgbg = cv2.createBackgroundSubtractorMOG2()

while(1):
    ret, frame = cap.read()

    fgmask = fgbg.apply(frame)
 
    cv2.imshow('fgmask',frame)
    cv2.imshow('frame',fgmask)

    
    k = cv2.waitKey(30) & 0xff
    if k == 27:
        break
    

cap.release()
cv2.destroyAllWindows()

KeyboardInterrupt: 